# python.setup.py
#
# Job responsible for running Python steps for Linux and macOS. The jobs are responsible for
#
#  * Building, linting and testing on Linux and macOS for various Python versions
#  * Releasing on-demand the Python package to PyPI
#    * This can be achieved by triggering a manual build and providing a queue variable 'release: true'
#

parameters:
  # Name of 'Service connection' defined in Azure DevOps project settings
  # See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/twine-authenticate?view=azure-devops#arguments
  pypiConnector: "testpypi-tomtom-dev"

jobs:
- job: 'Linux'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get install --no-install-recommends -y \
        git gcc musl-dev curl libldap2-dev libsasl2-dev openssh-client
    displayName: 'Install system dependencies'
  - template: ../steps/python/python.build.yml


- job: 'macOS'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'macos-10.13'
  steps:
  - template: ../steps/python/python.build.yml


- job: 'Windows'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ../steps/python/python.build.yml

- job: 'ReleaseChecks'
  dependsOn:
    - macOS
    - Linux
    - Windows
  pool:
    vmImage: 'ubuntu-16.04'
  condition: and(succeeded('macOS'), succeeded('Windows'), succeeded('Linux'), eq(variables['build.reason'], 'PullRequest'))
  steps:
  - template: ../steps/python/python.release.checks.yml


- job: 'Release'
  dependsOn:
    - macOS
    - Linux
    - Windows
  condition: and(succeeded('macOS'), succeeded('Windows'), succeeded('Linux'), succeeded('ReleaseChecks'), ne(variables['build.reason'], 'PullRequest'), eq(variables['release'], 'true'))
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: ../steps/python/python.release.yml
    parameters:
      pypiConnector: "${{ parameters.pypiConnector }}"
