# python.setup.py
#
# Job responsible for running Python steps for Linux and macOS. The jobs are responsible for
#
#  * building, linting and testing on Linux and macOS for various Python versions
#  * publishing the Python package to PyPI
#

parameters:
  pypiConnector: "testpypi-tomtom-dev"

jobs:
- job: 'Linux'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get install --no-install-recommends -y \
        git gcc musl-dev curl libldap2-dev libsasl2-dev openssh-client
    displayName: 'Install system dependencies'
  - template: ../steps/python/python.build.yml


- job: 'macOS'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'macos-10.13'
  steps:
  - template: ../steps/python/python.build.yml


- job: 'Publish'
  dependsOn:
    - macOS
    - Linux
  condition: and(succeeded('macOS'), succeeded('Linux'), ne(variables['build.reason'], 'PullRequest'))
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: ../steps/python/python.publish.yml
    parameters:
      pypiConnector: "${{ parameters.pypiConnector }}"
